// type for get data from api
export const GET_STUDENT_DATA_PENDING = "GET_STUDENT_DATA_PENDING";
export const GET_STUDENT_DATA_REJECTED = "GET_STUDENT_DATA_REJECTED";
export const GET_STUDENT_DATA_SUCCESSFULL = "GET_STUDENT_DATA_SUCCESSFULL";

// send data  to the server
export const SEND_DATA_PANDING = "SEND_DATA_PANDING";
export const SEND_DATA_REJECTED = "SEND_DATA_REJECTED";
export const SEND_DATA_SUCCESSFULL = "SEND_DATA_SUCCESSFULL";

// Delete data form server
export const DELETED_DATA_PANDING = "DELETED_DATA_PANDING";
export const DELETED_DATA_REJECTED = "DELETED_DATA_REJECTED";
export const DELETED_DATA_SUCCESSFULL = "DELETED_DATA_SUCCESSFULL";

// Edit and Update data
export const EDIT_DATA_PANDING = "EDIT_DATA_PANDING";
export const EDIT_DATA_REJECTED = "EDIT_DATA_REJECTED";
export const EDIT_DATA_SUCCESSFULL = "EDIT_DATA_SUCCESSFULL";
